### PR TITLE
Add Polish translation

### PR DESCRIPTION
**Pull request by TheLich132**
Tested on a large folder of photos, worked flawlessly.

Would fix/satisfy issue #1

### CODE REVIEW

**Comment by Merrit** [comment]
Hi @TheLich132 ! Thanks for the pull request :)

I took a look and it seems like exiv2 is a library as well as a command line application; it seems as though the library is the only part that is a dependency of plasma.

`exiv2` is not a known command on my system unless I explicitly install the command line package.

Does this work for you without having to install exiv2?

**Comment by TheLich132** [comment]
Without installing exiv2 it doesn't work unfortunately...
But I can change this PR to only provide translation if you want that. I made this change to exiv2, because at first I thought Arch doesn't provide ExifTool in perl-image-exiftool, because it was doing nothing after installing. But it was some stupid problem with perl not appending its binary directory to profile PATH. I fixed it and now it works with exiftool too.

**Comment by Merrit** [comment]
Ah okay.

Originally the thought was that we could use an already existing tool instead of requiring the user to download something new.. is there any compelling reason to use one of these tools over the other? I only chose exiftool at the time because it seemed to be more popular when I was searching. :woman_shrugging: 

If there is no specific reason to switch then yeah I am definitely happy to accept a translation :smiley:

**Comment by TheLich132** [comment]
It's ready to merge now. Translation only :)

**Comment by Merrit** [comment]
Looks good! Thanks for your contribution :)

**Pull request merged**
